# Generated by Django 5.1.7 on 2025-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='', max_length=100)),
                ('user_email', models.EmailField(default='', max_length=100)),
                ('user_age', models.IntegerField(default=0)),
            ],
        ),
    ]
